core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/urls.py
from django.urls import path
from .views import HomeView, AuthorsView, AuthorDetailView

app_name = "library"
urlpatterns = [
    path("", HomeView.as_view(), name='dashboard'),
    path("authors", AuthorsView.as_view(), name="authors"),
    path("author/<int:pk>", AuthorDetailView.as_view(),
         name="author_detail"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name} - Last login: {self.last_login}"

library/models.py
from django.db import models

# TODO: Add notifications and messages
# TODO: Notifications are for all
# TODO: Messages are perculiar to each user


class Category(models.Model):
    name = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    country = models.CharField(max_length=120)
    about = models.TextField(blank=True, null=True)
    headshot = models.ImageField(upload_to="static/images",
                                 null=True, blank=True)
    facebook = models.CharField(max_length=120, blank=True, null=True)
    twitter = models.CharField(max_length=120, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(max_length=120)
    authors = models.ManyToManyField(Author, related_name='books',
                                     db_table='book_author')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='books')
    synopsis = models.TextField(blank=True, null=True)
    volume = models.IntegerField(default=1)
    language = models.CharField(max_length=120)
    year = models.CharField(max_length=4)
    copies_owned = models.IntegerField(default=0)
    pages = models.IntegerField()
    link = models.URLField(blank=True)

    def __str__(self):
        return f"{self.title}, ({self.copies_owned})"


class MemberStatus(models.Model):
    status = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = "Member status"

    def __str__(self):
        return self.status


class Member(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    email_address = models.EmailField(blank=True, null=True)
    joined_date = models.DateTimeField(auto_now=True)
    active_status = models.ForeignKey(MemberStatus, on_delete=models.CASCADE,
                                      related_name="members")

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class ReservationStatus(models.Model):
    status = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = "Reservation status"

    def __str__(self):
        return self.status


class Reservation(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE,
                             related_name='reservations')
    member = models.ForeignKey(Member, on_delete=models.CASCADE,
                               related_name='reservations')
    reservation_date = models.DateTimeField(auto_now=True)
    reservation_status = models.ForeignKey(ReservationStatus,
                                           on_delete=models.CASCADE,
                                           related_name='reservations')

    def __str__(self):
        return f"{self.book} - {self.member}"


class LoanStatus(models.Model):
    status = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = "Loan status"

    def __str__(self):
        return self.status


class Loan(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE,
                             related_name="loans")
    member = models.ForeignKey(Member, on_delete=models.CASCADE,
                               related_name="loans")
    loan_date = models.DateTimeField(auto_now=True)
    loan_status = models.ForeignKey(LoanStatus, on_delete=models.CASCADE,
                                    related_name='loans')
    returned_date = models.DateTimeField(null=True)

    def __str__(self):
        return f"{self.book} - {self.member}"

payments/models.py
from django.db import models
from library.models import Member, Loan


class Fine(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE,
                               related_name='fines')
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE,
                             related_name="fines")
    date = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(max_digits=4, decimal_places=2)


class FinePayment(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE,
                               related_name='payments')
    fine = models.ForeignKey(Fine, on_delete=models.SET_NULL,
                             related_name="payments", null=True)
    payment_date = models.DateTimeField(auto_now=True)
    payment_amount = models.DecimalField(max_digits=10, decimal_places=2)

accounts/views.py
from django.shortcuts import render

# Create your views here.

library/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views import View
from .models import Author


class HomeView(View):
    def get(self, request):
        return render(request, "index.html")


class AuthorsView(ListView):
    model = Author
    context_object_name = 'authors'
    template_name = "library/author_list.html"


class AuthorDetailView(DetailView):
    model = Author
    template_name = "library/author_detail.html"
    context_object_name = 'author'

payments/views.py
from django.shortcuts import render

# Create your views here.

templates/library/author_detail.html
{% extends 'base.html' %}
{% load static %}



{% block title %}LibApp - Authors{% endblock title %}


{% block pagetitle %}Authors{% endblock pagetitle %}

{% block breadcrumb %}  
    <li class="breadcrumb-item"><a href="{% url 'library:dashboard' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'library:authors' %}">Authors</a></li>
    <li class="breadcrumb-item active">Author Details</li>
{% endblock breadcrumb %}


{% block content %}  
<section class="section profile">
    <div class="row">
      <div class="col-xl-4">

        <div class="card">
          <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

            <img src="{% static 'images/profile_picture.jpg' %}" alt="Profile" class="rounded-circle">
            <h2>{{ author.first_name }} {{ author.last_name }}</h2>
            <h6 class="text-success mt-1"><strong>Books - {{ author.books.all.count }}</strong></h6>
          </div>
        </div>

      </div>

      <div class="col-xl-8">

        <div class="card">
          <div class="card-body pt-3">
            <!-- Bordered Tabs -->
            <ul class="nav nav-tabs nav-tabs-bordered">

              <li class="nav-item">
                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
              </li>

              <li class="nav-item">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
              </li>

            </ul>
            <div class="tab-content pt-2">

              <div class="tab-pane fade show active profile-overview" id="profile-overview">
                <h5 class="card-title">About</h5>
                <p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p>

                <h5 class="card-title">Profile Details</h5>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label ">Full Name</div>
                  <div class="col-lg-9 col-md-8">{{ author.first_name }} {{ author.last_name }}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Country</div>
                  <div class="col-lg-9 col-md-8">{{ author.country }}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Facebook</div>
                  <div class="col-lg-9 col-md-8">{{ author.facebook }}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Twitter</div>
                  <div class="col-lg-9 col-md-8">{{ author.twitter }}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Email</div>
                  <div class="col-lg-9 col-md-8">{{ author.email }}</div>
                </div>

              </div>

              <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                <!-- Profile Edit Form -->
                <form>
                  <div class="row mb-3">
                    <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                    <div class="col-md-8 col-lg-9">
                      <img src="{% static 'img/profile-img.jpg' %}" alt="Profile">
                      <div class="pt-2">
                        <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                        <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                      </div>
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Full Name</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="fullName" type="text" class="form-control" id="fullName" value="Kevin Anderson">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="about" class="col-md-4 col-lg-3 col-form-label">About</label>
                    <div class="col-md-8 col-lg-9">
                      <textarea name="about" class="form-control" id="about" style="height: 100px">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</textarea>
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="company" class="col-md-4 col-lg-3 col-form-label">Company</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="company" type="text" class="form-control" id="company" value="Lueilwitz, Wisoky and Leuschke">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Job" class="col-md-4 col-lg-3 col-form-label">Job</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="job" type="text" class="form-control" id="Job" value="Web Designer">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Country" class="col-md-4 col-lg-3 col-form-label">Country</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="country" type="text" class="form-control" id="Country" value="USA">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Address" class="col-md-4 col-lg-3 col-form-label">Address</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="address" type="text" class="form-control" id="Address" value="A108 Adam Street, New York, NY 535022">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Phone" class="col-md-4 col-lg-3 col-form-label">Phone</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="phone" type="text" class="form-control" id="Phone" value="(436) 486-3538 x29071">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="email" type="email" class="form-control" id="Email" value="k.anderson@example.com">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Twitter" class="col-md-4 col-lg-3 col-form-label">Twitter Profile</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="twitter" type="text" class="form-control" id="Twitter" value="https://twitter.com/#">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Facebook" class="col-md-4 col-lg-3 col-form-label">Facebook Profile</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="facebook" type="text" class="form-control" id="Facebook" value="https://facebook.com/#">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Instagram" class="col-md-4 col-lg-3 col-form-label">Instagram Profile</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="instagram" type="text" class="form-control" id="Instagram" value="https://instagram.com/#">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin Profile</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="linkedin" type="text" class="form-control" id="Linkedin" value="https://linkedin.com/#">
                    </div>
                  </div>

                  <div class="text-center">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                  </div>
                </form><!-- End Profile Edit Form -->

              </div>

              <div class="tab-pane fade pt-3" id="profile-settings">

                <!-- Settings Form -->
                <form>

                  <div class="row mb-3">
                    <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                    <div class="col-md-8 col-lg-9">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="changesMade" checked>
                        <label class="form-check-label" for="changesMade">
                          Changes made to your account
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="newProducts" checked>
                        <label class="form-check-label" for="newProducts">
                          Information on new products and services
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="proOffers">
                        <label class="form-check-label" for="proOffers">
                          Marketing and promo offers
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                        <label class="form-check-label" for="securityNotify">
                          Security alerts
                        </label>
                      </div>
                    </div>
                  </div>

                  <div class="text-center">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                  </div>
                </form><!-- End settings Form -->

              </div>

              <div class="tab-pane fade pt-3" id="profile-change-password">
                <!-- Change Password Form -->
                <form>

                  <div class="row mb-3">
                    <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="password" type="password" class="form-control" id="currentPassword">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="newpassword" type="password" class="form-control" id="newPassword">
                    </div>
                  </div>

                  <div class="row mb-3">
                    <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                    <div class="col-md-8 col-lg-9">
                      <input name="renewpassword" type="password" class="form-control" id="renewPassword">
                    </div>
                  </div>

                  <div class="text-center">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                  </div>
                </form><!-- End Change Password Form -->

              </div>

            </div><!-- End Bordered Tabs -->

          </div>
        </div>

      </div>
    </div>
  </section>
{% endblock content %}

templates/library/author_list.html
{% extends 'base.html' %}
{% load static %}



{% block title %}LibApp - Authors{% endblock title %}


{% block pagetitle %}Authors{% endblock pagetitle %}

{% block breadcrumb %}  
    <li class="breadcrumb-item"><a href="{% url 'library:dashboard' %}">Home</a></li>
    <li class="breadcrumb-item active">Authors</li>
{% endblock breadcrumb %}
<!-- 
    {% block section_class %}
    <section class="section dashboard">
    {% endblock section_class %} -->

    
        {% block content %}
        <div class="card pt-3">
            <div class="card-body">
              <!-- Table with stripped rows -->
              <table class="table table-striped table-hover myTable">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Country</th>
                    <th>No. of Books</th>
                    <!-- <th data-type="date" data-format="YYYY/DD/MM">Start Date</th> -->
                    <!-- <th>Completion</th> -->
                  </tr>
                </thead>
                <tbody>
                
                {% for author in authors %}
                <tr>
                    <td><a href="{% url 'library:author_detail' author.pk %}">{{ author.first_name }} {{ author.last_name }}</a></td>
                    <td>{{ author.country }}</td>
                    <td>{{ author.books.all.count }}</td>
                    <!-- <td>2005/02/11</td> -->
                    <!-- <td>37%</td> -->
                </tr>
                {% endfor %}
                    
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
        {% endblock content %}